RS = [1, 0.2, 0.15, 0.1, 0.05];
PM = [1, 2, 3, 4, 5];
pmS = polyfit(PM,log(RS),2);
rs = polyval(pmS,PM);
figure('Units', 'pixels', ...
    'Position', [100 200 500 375]);
hold on
sfitRS = line(PM,RS);
set(sfitRS,...
    'LineStyle','none',...
    'Marker','o',...
    'MarkerSize',10,...
    'MarkerEdgeColor',[0.3 0.3 0.3])
hold on
LOBF = plot(PM,rs); %line of best fit
set(gca, ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XGrid'       , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'YScale'      , 'log'     , ...
  'LineWidth'   , 1         );

%%
RS = [1, 0.2, 0.15, 0.1, 0.05];
PM = [1, 2, 3, 4, 5];
f = @(b,x) exp(b(1)) .* exp(b(2).*x) + b(3);                % Exponential Fit With Y-Offset
B = fminsearch(@(b) norm(RS - f(b,PM)), [1; 1; 1]);         % Estimate Parameters
figure
plot(PM, RS, 'p')
hold on
plot(PM, f(B,PM), '-r')
hold off
grid