! Program to test the go to command
! written on 08/11/2022
! Salomon 

PROGRAM GOTOLINE

	CHARACTER PASS*20
	PRINT*, 'ENTER PASSPHRASE'
	READ*,  PASS
	SELECT CASE (PASS)
		CASE ('YES')
		PRINT*, 'JUMP TO SOME CONDITION'
		GO TO 15
		CASE DEFAULT
		PRINT*, 'YOU ENTERED SOME STATEMENT THAT DOES NOT DO &
			 ANYTHING'
	END SELECT

	IF (PASS == 'NON') THEN
		PRINT*, 'WRONG PASSPHRASE'
		15 PRINT*, 'YES THAT IS GOOD !'
	END IF
END PROGRAM GOTOLINE
